### ISSUE TITLE
Not compatible with Nightly 59.0a1

### ISSUE THREAD

**Issue by CFBancroft** [Loirooriol/Z-Notifier#13]
Should change 59.0 to 59.* or 60?
to make it work?
I did try to install nightly with your ZN 2... 
that what I got it.
Thanks

**Comment by Loirooriol** [comment]
Strange, it works for me. Did you modify the preferences in about:config?

**Comment by CFBancroft** [comment]
I did follow ZN README.md... true true false false...
see screenshot.
<img width="375" alt="not-compatible" src="https://user-images.githubusercontent.com/30822004/34084035-3b41ad32-e3bd-11e7-9343-c3cb8f605676.png">


-------------------------------
I notice that
extensions.legacy.exceptions ...

{972ce4c6-7e08-4474-a285-3208198ce6fd},testpilot@cliqz.com,@testpilot-containers,jid1-NeEaf3sAHdKHPA@jetpack,@activity-streams,pulse@mozilla.com,@testpilot-addon,@min-vid,tabcentertest1@mozilla.com,snoozetabs@mozilla.com,speaktome@mozilla.com,hoverpad@mozilla.com (should add Znotifier numbers here {numbers}?)

-------------------------------
browser.tabs.remote.autostart.2  modified boolean  false (should I change to true?)

-------------------------------
I am using Mac with FFN 59.0a1 (2017-12-17) (64-bit)

**Comment by Loirooriol** [comment]
`browser.tabs.remote.autostart.1` and `browser.tabs.remote.autostart.2` were old properties that should be ignored in 59 in favor of `browser.tabs.remote.autostart`.

If you go to `about:support`, does "Multiprocess Windows" say "0/n (Disabled)"?

**Comment by CFBancroft** [comment]
<img width="733" alt="multiprocess-windows" src="https://user-images.githubusercontent.com/30822004/34084148-2367e17a-e3bf-11e7-8a9a-c6ea43eec1ca.png">

**Comment by CFBancroft** [comment]
I notice that when I set false on extensions.allow-non-mpc-extensions, when I restart firefox and revert to true.
so I did trying load ZN2 in false... I got "not compatible".

**Comment by CFBancroft** [comment]
<img width="962" alt="play-with-it-successful" src="https://user-images.githubusercontent.com/30822004/34084297-f86e1622-e3c0-11e7-9a86-4fb874140895.png">

THANK YOU!

**Comment by Loirooriol** [comment]
You're welcome. How did you solve this?

**Comment by CFBancroft** [comment]
<img width="366" alt="nightly-default" src="https://user-images.githubusercontent.com/30822004/34085329-4a305b62-e3d2-11e7-8f13-c570c83f238f.png">
If I mistake open FF 57 and I open FFN, it reverts true to false and true to false... 
So I set Nightly as Default Browser, I hope it solved the problem. 
Thanks for taking notice "about:support".
