### ISSUE TITLE
ZN2 => Options => Import-Export ... not working

### ISSUE THREAD

**Issue by CFBancroft** [Loirooriol/Z-Notifier#14]
I did trying import button and did not show up for me to choose from the file.
BUT...
I am able to save on "Add", I did test one account it seems works fine.
BUT AGAIN...
I am NOT able to Export one host(AOL) that I did a test.

I guess have issue Import and Export buttons.

**Comment by Loirooriol** [comment]
This is like 4f51f37d18296326b48fd2603f6356c552f8e8c9, it seems I missed some cases.

**Comment by Loirooriol** [comment]
Fixed in c095dddacfbc5a8b1677374001783e4c7fc07743.
