### ISSUE TITLE
Hotmail beta doesn't work

### ISSUE THREAD

**Issue by Loirooriol** [Loirooriol/Z-Notifier#30]
*From @icegenie at 2018-06-30T19:57:06Z, originally posted in #12*

Hi, today one of my Hotmail account was upgraded to the new beta version with no possibility of going back to the old one. Since, it stays greyed out in Z-notifier, if I click on it I'm sent to the inbox, but in the extension it stays red with the can't verify error message.

**Comment by Loirooriol** [comment]
*From @Loirooriol at 2018-06-30T20:03:23Z*

@icegenie Why "with no possibility of going back"? I have a button saying "Try the beta" and I can toggle it.

**Comment by Loirooriol** [comment]
*From @icegenie at 2018-06-30T20:27:14Z*

I guess it's not beta anymore and they are starting to move accounts to the new version permanently.

**Comment by icegenie** [comment]
Just saw that Jeroen updated his hotmail.js script to fix this problem back in June. It can be downloaded on the X-notifier forum.
